#!/usr/bin/env bash
# A bash script that tranfers a file from a client to a server

if [ "$#" -lt 3 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

#Variables based on user input
path_to_file="$1"
remote_user="$2"
remote_host="$3"
directory="~/"
key="$4"

scp -i "$key" -o StrictHostKeyChecking=no "$path_to_file" "$remote_user@$remote_host:$directory"
