#!/usr/bin/env bash
# Install nginx on my server
echo "Installing Nginx and configuring redirections"
#updates and installation
sudo apt-get update -y -qq && \
         sudo apt-get install nginx -y
#restarting the service
sudo service nginx start
#allow nginx on firewall
sudo ufw allow "Nginx HTTP"
#add hello world
sudo echo -e "Hello World!" > /var/www/html/index.html
#set up nginx config
NGINX_CONF="/etc/nginx/sites-available/default"
#back up the file
sudo cp $NGINX_CONF "$NGINX_CONF.bak"
sudo bash -c "cat > $NGINX_CONF" <<EOL
server {
    listen 80;
    server_name 100.25.37.14;

    #redirection
    location /redirect_me/ {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
    #Default root & index config
    location / {
        root /var/www/html;
        index index.html index.htm;
        }
}
EOL
#test config
sudo nginx -t 
service nginx restart
echo "Redirection complete"
