#!/usr/bin/env bash
#A script to set up a haproxy load balancer

#update and install haproxy
sudo apt-get update -y -qq && \
         sudo apt-get install haproxy -y

HA_PROXY_CONF="/etc/haproxy/haproxy.cfg"
#back up the config
sudo cp $HA_PROXY_CONF "$HA_PROXY_CONF.bak"
#Add directives in the config
sudo bash -c "cat > $HA_PROXY_CONF" <<EOL
defaults
  mode http
  timeout client 15s
  timeout connect 10s
  timeout server 15s
  timeout http-request 10s

frontend my_front_end
    bind *:80
    default_backend web_servers 

backend web_servers
        balance roundrobin
        server 165003-web-01 100.25.37.14:80 check
        server 165003-web-02 52.91.149.92:80 check
EOL
sudo systemctl haproxy restart
sudo systemctl enable haproxy
