#!/usr/bin/env bash
# ping the google dns 5 times using a positional argument in a bash
# script
if [ "$#" -lt 1 ]; then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
	exit 1
fi
ping -c 5 "$1"
