#!/usr/bin/env bash
# Fix the server so that it listens to port 80
echo -e "sudo apt-get update -y -qq\nsudo apt-get install nginx -y\nsudo ufw allow \"Nginx HTTP\"\n" | bash
sudo service nginx restart

