#!/usr/bin/env bash
# Fix the server so that it listens to port 80
echo -e "sudo apt-get update -y -qq\nsudo apt-get install nginx -y\nsudo ufw allow \"Nginx HTTP\"\necho -e \"server {\\n    listen 80;\\n    listen [::]:80;\\n    server_name _;\\n}\" | sudo tee /etc/nginx/sites-available/default\nsudo nginx -t\nsudo service nginx restart" | bash
sudo service nginx restart

