#!/usr/bin/env bash
# A script that:
# Creates the file /var/run/myscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/myscript.pid and terminates itself when
# receiving a SIGQUIT or SIGTERM signal
remove() {
	echo "I hate the kill command"
	sudo rm -f /var/run/myscript.pid
	exit 0
}
trap "echo 'I hate the kill command'; remove" SIGTERM
trap "echo Y U no love me?!" SIGINT
echo $$ > /var/run/myscript.pid
while true
do
	echo "To infinity and beyond"
	sleep 2
done
