#!/usr/bin/env bash
# Install nginx on my server
echo "Installing Nginx and configuring redirections"
#updates and installation
sudo apt-get update -y -qq && \
         sudo apt-get install nginx -y

#Crate the nginx user
echo "Creating the nginx user"
sudo add user nginx

#Owership rights
sudo chown -R nginx:nginx /var/log/nginx
sudo chown -R nginx:nginx /var/lib/nginx
#restarting the service
sudo service nginx start
#allow nginx on firewall
sudo ufw allow "Nginx HTTP"
#set up nginx config
NGINX_CONF="/etc/nginx/sites-available/default"
#back up the file
sudo cp $NGINX_CONF "$NGINX_CONF.bak"
sudo bash -c "cat > $NGINX_CONF" <<EOL
user nginx;
worker_processes auto;

server {
    listen 8080;
    listen [::]:8080; 
    server_name _;

    #Default root & index config
    location / {
        root /var/www/html;
        index index.html index.htm;
        }
}
EOL
#test config
sudo nginx -t 
service nginx restart
echo "Nginx setup with non root user complete"
