#!/usr/bin/env bash
#install iginx, listen to 8080 as user nginx
echo -e "sudo apt-get update -y\nsudo apt-get install -y nginx\nsudo useradd -r -s /sbin/nologin nginx"  
sudo sed -i 's/user .*/user nginx\n/' /etc/nginx/nginx.conf  
echo 'listen 8080' | sudo tee /etc/nginx/sites-available/default  
sudo systemctl restart nginx

